[package]
name = "Lightning_Lending"
version = "1.0.23-beta"
license = "MIT"
authors = ["22388"]
description = "A lightning lending library & cli by Nostr/LDK/DLCs"
repository = "https://github.com/AreaLayer/Lightning_Lending"
documentation = "https://docs.rs/lightning_lending"
keywords = ["lightning", "lending", "lnd", "bitcoin", "dlc", "nostr"]
categories = ["cryptography", "Bitcoin", "Lightning"]
edition = "2021"


[dependencies]
dlc = "=0.7.1"
lightning = "=0.1.1"
nostr = "=0.39.0"
bdk = "= 0.30.2"
env_logger = "=0.11.6"
wasm-pack = "=0.13.1"
miniscript = "=12.3.0"
lightning-liquidity = "=0.1.0"
cln-plugin = "0.3.0"
clap = "=4.5.31"
anyhow = "1.0.97"
esplora-client = "0.11.0"
idna = "1.0.0"
openssl = "0.10.71"

[[bin]]
name = "lightning_lendingd"
path = "src/bin/lightning_lendingd.rs"
