[package]
name = "Lightning_Lending"
version = "1.0.4-beta"


[dependencies]
rust_dlc = "0.4.0"
ldk = "0.0.117"
nostr = "0.23"

[[bin]]
name = "cli"
path = "core/main.rs"

[dlc]

bitcoin = { version = "0.29.2", default-features = false }
dlc = { version = "0.4.0", path = "../dlc", default-features = false }
lightning = { version = "0.0.116", default-features = false }
secp256k1-zkp = {version = "0.7.0"}
serde = {version = "1.0", features = ["derive"], optional = true}

[ldk]

bech32 = { version = "0.9.0", default-features = false }
lightning = { version = "0.0.117-alpha2", path = "../lightning", default-features = false }
secp256k1 = { version = "0.24.0", default-features = false, features = ["recovery", "alloc"] }
num-traits = { version = "0.2.8", default-features = false }
bitcoin_hashes = { version = "0.11", default-features = false }
hashbrown = { version = "0.8", optional = true }
serde = { version = "1.0.118", optional = true }
bitcoin = { version = "0.29.0", default-features = false }

[nostr]
default = ["all-nips"]
blocking = ["async-utility/blocking", "nostr/blocking"]
all-nips = ["nip04", "nip05", "nip06", "nip11", "nip46", "nip47"]
nip03 = ["nostr/nip03"]
nip04 = ["nostr/nip04"]
nip05 = ["nostr/nip05"]
nip06 = ["nostr/nip06"]
nip11 = ["nostr/nip11"]
nip44 = ["nostr/nip44"]
nip46 = ["nostr/nip46"]
nip47 = ["nostr/nip47"]
