[package]
name = "Lightning_Lending"
version = "1.0.12-beta"
license = "MIT"
authors = ["22388"]
description = "A lightning lending library & cli by Nostr/LDK/DLCs"
repository = "https://github.com/AreaLayer/Lightning_Lending"
documentation = "https://docs.rs/lightning_lending"
keywords = ["lightning", "lending", "lnd", "bitcoin", "dlc", "nostr"]
categories = ["cryptography", "Bitcoin", "Lightning"]


[dependencies]
dlc = "=0.5.0"
lightning = "=0.0.123"
nostr = "=0.33.0"
bdk = "=1.0.0-beta.1"
env_logger = "=0.11.5"
rust = "1.80.0"



[[bin]]
name = "lightning_lendingd"
path = "src/bin/lightning_lendingd.rs"
