[package]
name = "Lightning_Lending"
version = "1.0.15-beta"
license = "MIT"
authors = ["22388"]
description = "A lightning lending library & cli by Nostr/LDK/DLCs"
repository = "https://github.com/AreaLayer/Lightning_Lending"
documentation = "https://docs.rs/lightning_lending"
keywords = ["lightning", "lending", "lnd", "bitcoin", "dlc", "nostr"]
categories = ["cryptography", "Bitcoin", "Lightning"]


[dependencies]
dlc = "=0.5.0"
lightning = "=0.0.124"
nostr = "=0.34.1"
bdk = "=1.0.0-alpha.11"
env_logger = "=0.11.5"
wasm-pack = "=0.13.0"
miniscript = "=12.2.0"
lightning-liquidity = "=0.1.0-alpha.4"


[[bin]]
name = "lightning_lendingd"
path = "src/bin/lightning_lendingd.rs"
