[package]
name = "Lightning_Lending"
version = "1.0.19-beta"
license = "MIT"
authors = ["22388"]
description = "A lightning lending library & cli by Nostr/LDK/DLCs"
repository = "https://github.com/AreaLayer/Lightning_Lending"
documentation = "https://docs.rs/lightning_lending"
keywords = ["lightning", "lending", "lnd", "bitcoin", "dlc", "nostr"]
categories = ["cryptography", "Bitcoin", "Lightning"]
edition = "2021"


[dependencies]
dlc = "=0.7.0"
lightning = "=0.0.125"
nostr = "=0.37.0"
bdk = "=1.0.0-alpha.11"
env_logger = "=0.11.5"
wasm-pack = "=0.13.1"
miniscript = "=12.3.0"
lightning-liquidity = "=0.1.0-alpha.6"
cln-plugin = "0.2.0"
clap = "=4.5.21"
anyhow = "1.0.93"
esplora-client = "0.11.0"

[[bin]]
name = "lightning_lendingd"
path = "src/bin/lightning_lendingd.rs"
